### ISSUE TITLE
Not Working on Newsletter Form

### ISSUE THREAD

**Issue by masoudilyas** [ProxiBlue/reCaptcha#38] opened 2019-06-14 11:18 UTC
Hi, 
I have installed the extension and got the recaptcha working fine on contact and customer registration form. I have added the code

```
>  <ul>
>    <?php echo $this->getChildHtml('recaptcha'); ?>
> </ul>

```
between the `<form>` tags in `subscribe.phtml`

However when i enter an email address and submit the form, it gives an error `Incorrect Captcha`
I am using the ultimo theme and Magento ver 1.9.4.1
Has anybody came across this error, and could you you guide me on how to fix it. 
Kind Regards
Masoud

**Comment by ProxiBlue** [comment] 2019-06-14 23:26
Do you have a running example?
If you look at the DOM, is the reCaptcha code outputted in the section?

**Comment by masoudilyas** [comment] 2019-06-15 09:40
Hi, the running example is http://www.lexifashion.co.uk/ecommerce/index.php/

**Comment by ProxiBlue** [comment] 2019-06-15 14:23
Hi,

You are using DISPLAY: NONE on the recapctha element. This will not work.
By making it display:none, you are removing it form the DOM, and the element fields will not post in the form POST data

Refer:  https://developers.google.com/recaptcha/docs/faq

![image](https://user-images.githubusercontent.com/4994260/59552620-f7c43c80-8fbb-11e9-9707-87ce8996d43f.png)

I removed the display:noen from teh css, to make the  element visible, and it worked 100%

I forced recapctha to appear (via setting the googlebot browser identifier), got the recpatcha challenges, and then subscribed 100%.

With forced:

![Selection_050](https://user-images.githubusercontent.com/4994260/59552529-c8610000-8fba-11e9-8108-2cd5918eba3b.png)
![Selection_051](https://user-images.githubusercontent.com/4994260/59552527-c5660f80-8fba-11e9-996c-3f95814dfd88.png)

Direct.

![Selection_049](https://user-images.githubusercontent.com/4994260/59552530-ceef7780-8fba-11e9-8b1f-ad0c2e887616.png)

I highly suspect your issue is that you have set the recaptcha element as display:none. 
It is very likely that the elements that hold teh captcha response is no longer submitted in your page, since they rae NOT IN THE DOM

![Selection_048](https://user-images.githubusercontent.com/4994260/59552539-f7777180-8fba-11e9-813c-4e666f66e518.png)

Also, you are violating the accepted usage policy from google reCapctha as you have hidden the element, but don't note anywhere that you DO use recaptcha. 

That is between you and google....but you accepted their usage policy when you chose to use reCaptcha

**Comment by masoudilyas** [comment] 2019-06-15 17:24
Thank you for the help, actually i am not a professional developer, i just implemented as per the instructions in the README, and it was working fine in contacts for and customer register, but it was not working in newsletter. I got a developer to have a look at it, and he says that he did some sort of override. I have asked him to reply on this thread, he can give more information as to what the issue was. I told him to hide the recaptcha badge as it was not displaying nicely. So i think the issue was fixed before you had a chance to test it.

**Comment by masoudilyas** [comment] 2019-06-15 17:42
Hi, the developer added this file 
```
<?php

class ProxiBlue_ReCaptcha_Block_Subscribe extends Mage_Newsletter_Block_Subscribe

{

	protected $_template = 'newsletter/subscribe.phtml';



    protected function _prepareLayout()

    {

        $captchaBlock = $this->getLayout()

            ->createBlock('captcha/captcha','recaptcha')->setFormId('newsletter_subscribe');

        $this->setChild('recaptcha',$captchaBlock);

        return $this;

    }

}
```
to `/app/code/community/ProxiBlue/ReCaptcha/Block/Subscribe.php` and it started working. 
I told him to hide the badge. I will keep the badge hidden and add the text and links as you have stated above.

**Comment by ProxiBlue** [comment] 2019-06-15 23:59
Hi,
glad you mad it work, however, I will note (so others don't do this)

Although you 'made it work' - how you did it is not correct. 

1. You have made edits to a 3rd party module, which is a bit nono - as you have now broken your upgradability. 6 months from now, you will want to update the module to get new feature, and forget you edited the file, and then suddenly your site is broken, and you go: How shit is magento! or How shit is that reCaptcha module, it keeps breaking.

2. The correct fix here will be to adjust the THEME layout files, via a custom directve, and place the correct layout directives in LAYOUT

You will most likely find that your theme is changing the layout (via layout directives)
The code placed simply ads the reCapctha block via code, which can be done via xml layout, and not need any code changes.

THIS:

https://github.com/ProxiBlue/reCaptcha/blob/master/app/design/frontend/base/default/layout/proxiblue_recaptcha.xml#L4

needs to be copied over, and placed correctly in your LAYOUTS, most likely local.xml

**Comment by ProxiBlue** [comment] 2019-06-15 23:59
I am closing the tcket, as the issue is not the recpatcha module, but your theme implementation.

**Closed by ProxiBlue** 2019-06-15 23:59 UTC

**Comment by masoudilyas** [comment] 2019-06-17 10:59
Hi thank you for the reply. As i said i am not a developer. I relayed your instructions to the dev, and he says that he tried that but it did not work. The newsletter subscribe form in my theme is being called from a cms block and not the layout, the same as you have done for the contact form. Quote 

> I already tried this, the problem is, the subscriber form is being called from cms static block and not using layout. Its like this. 
> 
> {{block type="proxiblue_recaptcha/subscribe" template="newsletter/subscribe.phtml" name="ultimonewsletter"}} 
> 
> Instead of calling from layout, they also done this for contact form in the module i think. Ask them if they have alternative to make layout call for cms.
