### ISSUE TITLE
 Issue with product review tab

### ISSUE THREAD

**Issue by tumazul** [ProxiBlue/reCaptcha#7] opened 2017-03-13 15:28 UTC
Hi,
I have an issue with product review. Ex : http://www.gateau-bonbon.com/meli-melo-bonbons.html
It's work well for product review with url :
http://www.gateau-bonbon.com/review/product/list/id/1/
But not for product review in tab :
http://www.gateau-bonbon.com/meli-melo-bonbons.html
 
Can you help me please ?
thanks
regards

**Comment by ProxiBlue** [comment] 2017-03-14 07:05
hi,

this is not a bug with the module code.
You are using a custom theme, which is using custom layouts to place the reviews in a tab.

As described in this section of the readme: 

https://github.com/ProxiBlue/reCaptcha#captcha-is-still-not-appearing-even-after-i-did-the-steps-above

you need to find the layout directives that define your reviews tab, and insert the relevant layout xml for the recaptcha block into that layout directive (so adding the block), and then locate the reviews tab .phtml, and insert the require block output code (the echo of the child html part)

In some cases you could insert the recapctha block into a parent block that is a text_list, thus no need to also place the echo output of teh new child block.

Unfortunately the issue you have is beyond the help I can provide as the theme could be doing the tab in a couple of ways (even programatically, if not by layout xml, but that is unlikely)

If you have no idea what all that means, you need to locate a developer who can do this for you. It IS relatively easy to do, I just don't have the time.

Closing as this is not a bug, but a theme integration issue

**Closed by ProxiBlue** 2017-03-14 07:05 UTC
