### ISSUE TITLE
newsletter issue with custom layout

### ISSUE THREAD

**Issue by tryllu** [ProxiBlue/reCaptcha#42] opened 2019-12-19 07:26 UTC
Hi, we have some problems running recaptcha on main page, and after long investigation we have to ask for help.

CMS page does include following:
`{{block type="newsletter/subscribe" template="newsletter/home_newside_subscribe.phtml"}}`

It is not being referenced in layout files.

Adding `<?php echo $this->getChildHtml('recaptcha'); ?>` in form, in phtml does not work.

Any help? :)

**Comment by ProxiBlue** [comment] 2019-12-19 07:36
Hi,

The problem is that you are not inserting the reCaptcha block as a child block (which is normally done via layout directives)

example:

https://github.com/ProxiBlue/reCaptcha/blob/master/app/design/frontend/base/default/layout/proxiblue_recaptcha.xml#L4

What you will need to do (PR welcomed) is to duplicate the way Contacts work if embeded via a block tag into CMS pages

See this block class

https://github.com/ProxiBlue/reCaptcha/blob/master/app/code/community/ProxiBlue/ReCaptcha/Block/Contact.php

Duplicate that as class Newsletter.php and adjust the class to extend the usual Core newsletter block

```
class ProxiBlue_ReCaptcha_Block_Contact extends Mage_Newsletter_Block_Subscribe {
```

and change the ```setFormId('user_contact')``` to be ```setFormId('newsletter_subscribe')```

(ref: https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/Newsletter/Block/Subscribe.php)

Then, use this new block in the block notation

```
{{block type="proxiblue_recaptcha/newsletter" template="newsletter/home_newside_subscribe.phtml"}}
```

This will then use the ```_prepareLayout()``` in that new class to inject the child recapctha block programatically

**Comment by ProxiBlue** [comment] 2019-12-19 07:39
potentially ratther use 'Subscribe.php' in place of `Newsletter.php` and use _Subscribe in class name to keep more in-line with core naming conventions ;)

**Comment by tryllu** [comment] 2019-12-19 07:57
Great. It started to work.

However reCaptcha widget is blocking view. When mouse over newsletter form it jumps from left/right corner. CSS?

**Comment by ProxiBlue** [comment] 2019-12-19 08:09
Check admin settings, you can set the position of the widget 
Bottom Right, Bottom Left or Inline

see if any of the options make it work better.

If not you'd likely need to check your DOM elements, as something sounds broken in the DOM

**Comment by ProxiBlue** [comment] 2019-12-19 08:11
potentially move where you are inserting the child block using ```<?php echo $this->getChildHtml('recaptcha'); ?>``` - likely it is encased in the input form element. 

You'd want to set it just before the closing ```</form>``` tag.

**Comment by ProxiBlue** [comment] 2019-12-19 08:13
also, try to wrap the output of ```<?php echo $this->getChildHtml('recaptcha'); ?>``` in ```<ul> ... </ul>``` tags, as the expected position of the recpatcha output is withing element lists, as itself is enacased in ```<li> </li>```

**Comment by tryllu** [comment] 2019-12-19 20:46
Yup, figured out that the problem is caused by second newsletter form on the left. On main page there are two newsletter forms. That in the footer is working fine however second one (on left side) overwrites some styling and causes badge malfunction.

Have you ever configured reCaptcha for two forms on one page?

**Comment by ProxiBlue** [comment] 2019-12-19 22:06
Sure have. The captcha works fine with a footer based newsletter form,
which appears on all pages, and thus any other page, like login.

See for example www.enjo.com.au

There is a footer on all pages.

**Comment by ProxiBlue** [comment] 2020-01-06 05:11
closed due to inactivity

**Closed by ProxiBlue** 2020-01-06 05:11 UTC
